### ISSUE TITLE
Diagnostics notebook for POP currently fails to run.

### ISSUE THREAD

**Issue by nusbaume** [NCAR/CESM-Tutorial#197]
The problem may be with the version of python being used, the NPL environment being used, or changes to the backend system that are causing the dask configuration to behave badly.  Will need to experiment to figure out what the exact problem is.

**Comment by dabail10** [comment]
There is a problem with the ib0 network interface. What should this be for dask?

cluster = dask_jobqueue.PBSCluster(
    cores=2,  # The number of cores you want
    memory="8GB",  # Amount of memory
    processes=1,  # How many processes
    queue="casper",  # The type of queue to utilize (/glade/u/apps/dav/opt/usr/bin/execcasper)
    # log_directory="/glade/derecho/scratch/deppenme/dask/",  # Use your local directory
    resource_spec="select=1:ncpus=1:mem=8GB",  # Specify resources
    project="P93300065",  # Input your project ID here
    walltime="02:00:00",  # Amount of wall time
    interface="ib0",  # Interface to use
)

**Comment by dabail10** [comment]
It worked if I just commented out the interface line.

**Comment by nusbaume** [comment]
Thanks @dabail10!  I just tried it myself with your changes and it worked for me too, so I will go ahead and close this issue.
