### ISSUE TITLE
Graphics of directory structure need to be updated to derecho directories.

### ISSUE THREAD

**Issue by dabail10** [NCAR/CESM-Tutorial#198]

**Comment by dabail10** [comment]
I'm not sure how these images were created.

**Comment by duvivier** [comment]
Some of the development documentation is here:
https://drive.google.com/drive/folders/1uQI2jV0p_AWL1oftSOIVCbHpBY3j4mtC

But if I recall correctly the final images were made in powerpoint by Cecile perhaps. Sorry this wasn't better documented...

**Comment by cecilehannay** [comment]
The images are based on a figure I created for a tutorial at CU. They were taken from the file: Tutorial-CU-2022-final_day1.pptx, which can be found at: [CESM-Tutorial/2023/Practical_activity_development](https://drive.google.com/drive/folders/1uQI2jV0p_AWL1oftSOIVCbHpBY3j4mtC)

However, I did not create the final figures as they appear on the website. I only provided the original PowerPoint, and the figures were created by someone else. (They were a simplified version of my original figures). If it wasn't Alice, it might have been Peter, as he was working on that section.

That said, I think I could take this task. I believe it wouldn't take me too much time to work on this. I will put stuff in: [CESM-Tutorial/2024/Materials-For-JupyterBook](https://drive.google.com/drive/folders/1nmrmbYs3y9e2y4K0KzL94Ch6iHo4j6ih?usp=drive_link).

**Comment by cecilehannay** [comment]
Also to document for future purposes: the figures needs to be done in powerpoint as there are formatting issues in using GoogleSlide. 

Final version should go back in: 
[CESM-Tutorial/2024/Materials-For-JupyterBook](https://drive.google.com/drive/folders/1nmrmbYs3y9e2y4K0KzL94Ch6iHo4j6ih?usp=drive_link).
