### ISSUE TITLE
Issue on page /notebooks/basics/basics_overview.html

### ISSUE THREAD

**Issue by jrya7** [NCAR/CESM-Tutorial#220]
In dark mode, the text in the blue box is hard to read, and possibly on other pages that use the `alert alert-info` class.

**Comment by cecilehannay** [comment]
We are aware of this issue. In the intro, we tell them to use the white background. 
https://ncar.github.io/CESM-Tutorial/notebooks/intro/intro_overview.html

**Comment by jrya7** [comment]
Ah sorry didn't see that page. I also had seen it on the [2023 page](https://ncar.github.io/CESM-Tutorial-2023/notebooks/basics/basics_overview.html) but the [current/live page](https://ncar.github.io/CESM-Tutorial/notebooks/basics/basics_overview.html) is better in dark mode.
